Repository f-lab-edu/unique-auction, pull requests merged in 2022-11, with the labels that each got.

#55 [#52] Feature: docker compose 및 testconainer 설정
  docker-compose.yml
  src/test/java/com/uniqueauction/AbstractContainerBaseTest.java
  src/test/java/com/uniqueauction/domain/login/LoginServiceTest.java
  src/test/java/com/uniqueauction/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/com/uniqueauction/domain/product/service/ProductServiceTest.java
  src/test/java/com/uniqueauction/domain/user/service/UserServiceTest.java
  src/test/java/com/uniqueauction/web/login/controller/LoginControllerTest.java
  src/test/java/com/uniqueauction/web/product/controller/ProductControllerTest.java
  src/test/java/com/uniqueauction/web/user/controller/UserControllerTest.java
Labels: feature

#63 [#62] Feature: Base Entity 추가
  mysql-init-files/schema.sql
  src/main/java/com/uniqueauction/UniqueAuctionApplication.java
  src/main/java/com/uniqueauction/domain/base/BaseEntity.java
  src/main/java/com/uniqueauction/domain/product/entity/Product.java
  src/main/java/com/uniqueauction/domain/review/Review.java
  src/main/java/com/uniqueauction/domain/trade/entity/Purchase.java
  src/main/java/com/uniqueauction/domain/trade/entity/Sale.java
  src/main/java/com/uniqueauction/domain/trade/entity/Trade.java
  src/main/java/com/uniqueauction/domain/user/entity/User.java
Labels: feature

#81 [#71] Refactor: application profile 분리, 운영환경 클라우드 서버 IP 적용
  build.gradle
  src/main/java/com/uniqueauction/domain/aop/LoginCheckAspect.java
  src/main/java/com/uniqueauction/domain/user/entity/User.java
  src/main/java/com/uniqueauction/exception/ErrorCode.java
  src/main/java/com/uniqueauction/exception/advice/CommonControllerAdvice.java
  src/main/java/com/uniqueauction/web/review/response/ReviewByUserResponse.java
  src/main/java/com/uniqueauction/web/user/controller/UserController.java
  src/main/resources/application.yml
  src/test/java/com/uniqueauction/TestContainerBase.java
  src/test/java/com/uniqueauction/domain/login/LoginServiceTest.java
  src/test/java/com/uniqueauction/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/com/uniqueauction/domain/product/service/ProductServiceTest.java
  src/test/java/com/uniqueauction/domain/user/service/UserServiceTest.java
  src/test/java/com/uniqueauction/web/login/controller/LoginControllerTest.java
  src/test/java/com/uniqueauction/web/product/controller/ProductControllerTest.java
  src/test/java/com/uniqueauction/web/user/controller/UserControllerTest.java
  src/test/resources/application-localtest.yml
  src/test/resources/application-test.yml
  src/test/resources/schema.sql
Labels: refactor

#91 [#80] Bug: 리뷰 등록 안되는 현상 수정
  src/main/java/com/uniqueauction/web/review/request/SaveReviewRequest.java
  src/main/java/com/utils/RegExpCode.java
Labels: bug

#90 [#78] Bug: 암호화 조건 명시 및 회원가입 에러 수정
  src/main/java/com/uniqueauction/web/user/request/JoinRequest.java
  src/main/java/com/uniqueauction/web/user/request/UpdateUserRequest.java
  src/main/java/com/utils/RegExpCode.java
  src/test/java/com/uniqueauction/web/user/controller/UserControllerTest.java
Labels: bug

#87 [#75] Bug: Service layerRquest Inejection Change
  src/main/java/com/uniqueauction/domain/user/service/UserService.java
  src/main/java/com/uniqueauction/web/user/controller/UserController.java
  src/main/java/com/uniqueauction/web/user/request/SaveUserRequest.java
  src/main/java/com/uniqueauction/web/user/request/UpdateUserRequest.java
  src/test/java/com/uniqueauction/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/uniqueauction/domain/user/service/UserServiceTest.java
  src/test/java/com/uniqueauction/web/user/controller/UserControllerTest.java
Labels: bug
