Repository f-lab-edu/unique-auction, pull requests merged in 2022-10, with the labels that each got.

#16 [#15] Feature: 구매 판매 엔티티 및 Bid(입찰) 구현
  src/main/java/com/uniqueAuction/domain/trade/entity/Purchase.java
  src/main/java/com/uniqueAuction/domain/trade/entity/PurchaseType.java
  src/main/java/com/uniqueAuction/domain/trade/entity/Sale.java
  src/main/java/com/uniqueAuction/domain/trade/entity/SaleType.java
  src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
  src/main/java/com/uniqueAuction/domain/trade/entity/TradeStatus.java
  src/main/java/com/uniqueAuction/domain/trade/repository/PurchaseRepository.java
  src/main/java/com/uniqueAuction/domain/trade/repository/PurchaseRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/trade/repository/SaleRepository.java
  src/main/java/com/uniqueAuction/domain/trade/repository/SaleRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/trade/service/PurchaseService.java
  src/main/java/com/uniqueAuction/domain/trade/service/SaleService.java
  src/main/java/com/uniqueAuction/domain/util/validator/PhoneValidator.java
  src/main/java/com/uniqueAuction/domain/util/validator/annotation/Phone.java
  src/main/java/com/uniqueAuction/web/trade/controller/PurchaseController.java
  src/main/java/com/uniqueAuction/web/trade/controller/SaleController.java
  src/main/java/com/uniqueAuction/web/trade/request/PurchaseBidRequest.java
  src/main/java/com/uniqueAuction/web/trade/request/SaleBidRequest.java
Labels: feature

#25 #24 not request under service
  src/main/java/com/uniqueAuction/domain/product/repository/ProductRepository.java
  src/main/java/com/uniqueAuction/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/product/service/ProductService.java
  src/main/java/com/uniqueAuction/web/product/controller/ProductController.java
  src/main/java/com/uniqueAuction/web/product/request/ProductSaveRequest.java
  src/main/java/com/uniqueAuction/web/product/request/ProductUpdateRequest.java
  src/main/java/com/uniqueAuction/web/response/CommonResponse.java
  src/test/java/com/uniqueAuction/web/product/controller/ProductControllerTest.java
Labels: feature

#30 [#18] Feature: Trade 즉시 구매, 판매 구현
  src/main/java/com/uniqueAuction/domain/trade/entity/Purchase.java
  src/main/java/com/uniqueAuction/domain/trade/entity/PurchaseType.java
  src/main/java/com/uniqueAuction/domain/trade/entity/Sale.java
  src/main/java/com/uniqueAuction/domain/trade/entity/SaleType.java
  src/main/java/com/uniqueAuction/domain/trade/entity/Trade.java
  src/main/java/com/uniqueAuction/domain/trade/entity/TradeStatus.java
  src/main/java/com/uniqueAuction/domain/trade/repository/PurchaseRepository.java
  src/main/java/com/uniqueAuction/domain/trade/repository/PurchaseRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/trade/repository/SaleRepository.java
  src/main/java/com/uniqueAuction/domain/trade/repository/SaleRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/trade/repository/TradeRepository.java
  src/main/java/com/uniqueAuction/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/com/uniqueAuction/domain/trade/service/PurchaseService.java
  src/main/java/com/uniqueAuction/domain/trade/service/SaleService.java
  src/main/java/com/uniqueAuction/exception/ErrorCode.java
  src/main/java/com/uniqueAuction/web/response/CommonResponse.java
  src/main/java/com/uniqueAuction/web/trade/controller/PurchaseController.java
  src/main/java/com/uniqueAuction/web/trade/controller/SaleController.java
  src/main/java/com/uniqueAuction/web/trade/request/PurchaseBidRequest.java
  src/main/java/com/uniqueAuction/web/trade/request/PurchaseRequest.java
  src/main/java/com/uniqueAuction/web/trade/request/SaleBidRequest.java
  src/main/java/com/uniqueAuction/web/trade/request/SaleRequest.java
Labels: feature

#26 #21 product api test code
  src/main/java/com/uniqueauction/domain/product/entity/Image.java
  src/main/java/com/uniqueauction/domain/product/entity/Product.java
  src/main/java/com/uniqueauction/domain/product/repository/ImageRepository.java
  src/main/java/com/uniqueauction/domain/product/repository/ImageRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/product/repository/ProductRepository.java
  src/main/java/com/uniqueauction/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/product/service/ImageService.java
  src/main/java/com/uniqueauction/domain/product/service/ProductService.java
  src/main/java/com/uniqueauction/domain/util/config/lombok.config
  src/main/java/com/uniqueauction/exception/advice/CommonControllerAdvice.java
  src/main/java/com/uniqueauction/web/product/controller/ProductController.java
  src/main/java/com/uniqueauction/web/product/request/ProductSaveRequest.java
  src/main/java/com/uniqueauction/web/product/request/ProductUpdateRequest.java
  src/test/java/com/uniqueauction/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/com/uniqueauction/domain/product/service/ProductServiceTest.java
  src/test/java/com/uniqueauction/web/login/controller/LoginControllerTest.java
  src/test/java/com/uniqueauction/web/product/controller/ProductControllerTest.java
Labels: feature

#38 [#37] Feature: Spring Data JPA 적용
  Dockerfile
  build.gradle
  docker-compose.yml
  settings.gradle
  src/main/java/com/uniqueauction/UniqueAuctionApplication.java
  src/main/java/com/uniqueauction/domain/aop/ValidationCheckAspect.java
  src/main/java/com/uniqueauction/domain/product/entity/Product.java
  src/main/java/com/uniqueauction/domain/product/entity/TradeItem.java
  src/main/java/com/uniqueauction/domain/product/repository/ProductRepository.java
  src/main/java/com/uniqueauction/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/product/repository/TradeItemRepository.java
  src/main/java/com/uniqueauction/domain/product/repository/TradeItemRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/product/service/ProductService.java
  src/main/java/com/uniqueauction/domain/product/service/TradeItemService.java
  src/main/java/com/uniqueauction/domain/trade/entity/Purchase.java
  src/main/java/com/uniqueauction/domain/trade/entity/Sale.java
  src/main/java/com/uniqueauction/domain/trade/entity/Trade.java
  src/main/java/com/uniqueauction/domain/trade/repository/PurchaseRepository.java
  src/main/java/com/uniqueauction/domain/trade/repository/PurchaseRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/trade/repository/SaleRepository.java
  src/main/java/com/uniqueauction/domain/trade/repository/SaleRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/trade/repository/TradeRepository.java
  src/main/java/com/uniqueauction/domain/trade/repository/TradeRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/trade/service/PurchaseService.java
  src/main/java/com/uniqueauction/domain/trade/service/SaleService.java
  src/main/java/com/uniqueauction/domain/user/entity/User.java
  src/main/java/com/uniqueauction/domain/user/repository/UserRepository.java
  src/main/java/com/uniqueauction/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/uniqueauction/domain/user/service/UserService.java
  src/main/java/com/uniqueauction/exception/ErrorCode.java
  src/main/java/com/uniqueauction/web/login/request/LoginRequest.java
  src/main/java/com/uniqueauction/web/product/controller/ProductController.java
  src/main/java/com/uniqueauction/web/product/request/ProductSaveRequest.java
  src/main/java/com/uniqueauction/web/product/request/ProductSearchRequest.java
  src/main/java/com/uniqueauction/web/product/request/ProductUpdateRequest.java
  src/main/java/com/uniqueauction/web/trade/controller/PurchaseController.java
  src/main/java/com/uniqueauction/web/trade/controller/SaleController.java
  src/main/java/com/uniqueauction/web/trade/request/PurchaseRequest.java
  src/main/java/com/uniqueauction/web/trade/request/SaleRequest.java
  src/main/java/com/uniqueauction/web/user/controller/UserController.java
  src/main/java/com/uniqueauction/web/user/request/JoinRequest.java
  src/main/java/com/uniqueauction/web/user/request/UpdateUserRequest.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/test/java/com/uniqueauction/UniqueAuctionApplicationTests.java
  src/test/java/com/uniqueauction/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/com/uniqueauction/domain/product/service/ProductServiceTest.java
  src/test/java/com/uniqueauction/domain/user/service/UserServiceTest.java
  src/test/java/com/uniqueauction/web/login/controller/LoginControllerTest.java
  src/test/java/com/uniqueauction/web/product/controller/ProductControllerTest.java
Labels: refactor

#42 refectory : 불필요한코드 제거 멘토님 요구사항
  .github/workflows/gradle.yml
  src/main/java/com/uniqueauction/UniqueAuctionApplication.java
  src/main/java/com/uniqueauction/domain/aop/ValidationCheckAspect.java
  src/main/java/com/uniqueauction/domain/product/entity/Product.java
  src/main/java/com/uniqueauction/domain/product/service/ProductService.java
  src/main/java/com/uniqueauction/domain/trade/entity/Purchase.java
  src/main/java/com/uniqueauction/domain/trade/entity/Sale.java
  src/main/java/com/uniqueauction/domain/trade/service/PurchaseService.java
  src/main/java/com/uniqueauction/domain/trade/service/SaleService.java
  src/main/java/com/uniqueauction/domain/user/service/UserService.java
  src/main/java/com/uniqueauction/exception/ErrorCode.java
  src/main/java/com/uniqueauction/web/login/controller/LoginController.java
  src/main/java/com/uniqueauction/web/login/request/LoginRequest.java
  src/main/java/com/uniqueauction/web/product/controller/ProductController.java
  src/main/java/com/uniqueauction/web/product/request/ProductSaveRequest.java
  src/main/java/com/uniqueauction/web/product/request/ProductUpdateRequest.java
  src/main/java/com/uniqueauction/web/response/CommonResponse.java
  src/main/java/com/uniqueauction/web/trade/request/PurchaseRequest.java
  src/main/java/com/uniqueauction/web/trade/request/SaleRequest.java
  src/main/java/com/uniqueauction/web/user/controller/UserController.java
  src/main/java/com/uniqueauction/web/user/request/UpdateUserRequest.java
  src/main/java/com/utils/RegExpCode.java
  src/main/java/com/utils/config/lombok.config
  src/test/java/com/uniqueauction/domain/login/loginServiceTest.java
  src/test/java/com/uniqueauction/domain/product/repository/ProductRepositoryImplTest.java
  src/test/java/com/uniqueauction/domain/product/service/ProductServiceTest.java
  src/test/java/com/uniqueauction/web/login/controller/LoginControllerTest.java
  src/test/java/com/uniqueauction/web/product/controller/ProductControllerTest.java
Labels: bug
